### ISSUE TITLE
Refactor the test of get related product by product_id

### ISSUE THREAD

**Issue by Zhaozhi233** [Agile-Organization/recommendations#100]
https://github.com/Agile-Organization/recommendations/blob/823030b7160148ea4b311d0610015e6b5f7aea42/tests/test_service.py#L163

Problem:
In line 183, the 'num_records' may reach 2 and the test will fail.
 We need fix this, and change the 'if-else ' function to make every case will be tested.

**Comment by lj894** [comment]
This should be fixed by #86 as well since we modified some of the test cases. Can someone verify?

**Comment by MinervaMint** [comment]
> This should be fixed by #86 as well since we modified some of the test cases. Can someone verify?

Yeah I think it is already resolved. Closing this story.
