### ISSUE TITLE
Query active related products by product id

### ISSUE THREAD

**Issue by Mu-xsan** [Agile-Organization/recommendations#15]
**As a** Developer
**I need** to query all the active related products by a given product id 
**So that** provided a product id, I can return all the products that has an active relationship with the searching product as recommendations.

**Assumptions:** 
* Each product has a unique id.
* Any two products may have a one way relationship defined by an integer (0 - up-sell, 1 - cross-sell, 2 - accessory)
* Given an order of product A and product B, there can be up to one relationship exists.
* Relationship can be toggled between active and inactive.

**Acceptance Criteria:**
```
Given the id of product A, returns all the records in database that has a relationship with A.
GET on /recommendations/{product-a-id}
Then returns an array that contains 3 objects
[
    {
        relationship-id: 0,
        ids: [id1, id2, id3, ...]
    },
    {
        relationship-id: 1,
        ids: [id4, id5, id6, ...]
    },
    {
        relationship-id: 2,
        ids: [id7, id8, id9, ...]
    }
]
For each category, if no related product exists, then ids field will be an empty array.
```

**Comment by sushanthsamala** [comment]
@MinervaMint Could you please add unit tests for this endpoint?
