### ISSUE TITLE
Fix the 500 errors in endpoints

### ISSUE THREAD

**Issue by MinervaMint** [Agile-Organization/recommendations#158]
**As a** ...  User
**I need** ...  to get bad request error for bad data
**So that** ...  I can be assured that the endpoints are working fine

**Assumptions:** 
* ... The current "Create", "Update", "Search" button endpoints throw 500 errors

**Acceptance Criteria:**
```
When ... I throw bad data at the endpoints
Then ... I should see 400 Bad Request error
```

**Comment by lj894** [comment]
Create button throw 500 if type invalid.

**Comment by lj894** [comment]
Update button throw 500 if type invalid.

**Comment by lj894** [comment]
Create a drop down for type input on the UI.

**Comment by lj894** [comment]
> Create a drop down for type input on the UI.
Fixed.
