### ISSUE TITLE
Query all related products by product id

### ISSUE THREAD

**Issue by lj894** [Agile-Organization/recommendations#18]
**As a** Developer
**I need** to query all the related products, include the one with inactive relationship, by a given product id. 
**So that** after provided a product id, I can return all the products that has an relationship with it as recommendations.

**Assumptions:** 
* Each product has an unique id.
* Any two products may have an one way relationship defined by an integer (0 - up-sell, 1 - cross-sell, 2 - accessory)
* Given an order of product A and product B, there can be up to one relationship exists.
* Relationship can be toggled between active and inactive.

**Acceptance Criteria:**
```
Given the id of product A, returns all the records in database that has a relationship with A.
GET on /recommendations/{product-a-id}
Then returns an array that contains 3 objects
[
    {
        relationship-id: 1,
        ids: [id1, id2, id3, ...],
        inactive-ids: [id10, id20, id30, ...]
    },
    {
        relationship-id: 2,
        ids: [id4, id5, id6, ...],
        inactive-ids: [id40, id50, id60, ...]
    },
    {
        relationship-id: 3,
        ids: [id7, id8, id9, ...],
        inactive-ids: [id70, id80, id90, ...]
    }
]
For each category, if no related product exists, then ids field will be an empty array.
```

**Comment by sushanthsamala** [comment]
This is broken  the endpoint does not work, how did you test it?
