### ISSUE TITLE
Query the relationship between 2 products

### ISSUE THREAD

**Issue by lj894** [Agile-Organization/recommendations#19]
**As a** Developer
**I need** to query the relationship between 2 products by given 2 product ids. 
**So that** after provided product id 1 and product id 2, I can return either an integer indicates the relationship type between the 2 product, or null as there is no active relationship between the 2 product.

**Assumptions:** 
* Each product has a unique id.
* Any two products may have a one way relationship defined by an integer (1 - up-sell, 2 - cross-sell, 3 - accessory)
* Given an order of product A and product B, there can be up to one relationship exists.
* Relationship can be toggled between active and inactive.

**Acceptance Criteria:**
```
Given the id of product A, and id of product B, returns either an 1, 2, 3 integer, or null.
GET on /recommendations/relationship?product1={product-id}&product2={product-id} 
Then returns one of the following: 1, 2, 3, null
```

**Comment by sushanthsamala** [comment]
@lj894 I feel the endpoint should return a serialized recommendation object if the relationship exists, if the recommendation does not exist it should return Null and a 204 NO_CONTENT status. Let me if you feel the previous approach is better.
