### ISSUE TITLE
Update status of a recommendation item

### ISSUE THREAD

**Issue by MinervaMint** [Agile-Organization/recommendations#20]
**As a** Developer
**I need** To be able to update the status of a recommendation item
**So that** I can set whether the recommendation is active

**Assumptions:** 
* Each product has a unique id
* A recommendation item has one integer field indicating its type (0 - up-sell, 1 - cross-sell, 2 - accessory)
* A recommendation can be either active or inactive, and such status can be toggled

**Acceptance Criteria:**
```
Given two product ids that have an associated recommendation item and the status to be set
When I use PUT method 
    PUT /recommendations/status
    {
      id1: ...,
      id2:...,
      status:...
    }
Then I can change the status of the item and return 200 + recommendation{...}
```

**Comment by sushanthsamala** [comment]
@MinervaMint I feel this endpoint is redundant we can directly update either status or typeid in the "PUT /recommendations" Update typeid endpoint. Let me know if you feel differently

**Comment by MinervaMint** [comment]
Yes I think you are right about this. I made a mistake spliting it as two stories. Thanks for pointing it out!
