### ISSUE TITLE
Add more unit tests

### ISSUE THREAD

**Issue by sushanthsamala** [Agile-Organization/recommendations#44]
**As a** ...  Developer
**I need** ...  Test coverage as close to 100% as possible
**So that** ...  I can automate my tests on a pipeline next sprint

**Assumptions:** 
* ... The current test coverage is less than 95%

**Acceptance Criteria:**
```
When ... I run nosetests
Then ... I should get at least 99% test coverage
```

**Comment by MinervaMint** [comment]
I just pulled the code and ran the nosetest it seems now everything in service.py and model.py is covered. 😆

**Comment by sushanthsamala** [comment]
> I just pulled the code and ran the nosetest it seems now everything in service.py and model.py is covered. 😆

Yeah I added all the required tests.
