### ISSUE TITLE
Add recommendation_id to as primary key to database schema

### ISSUE THREAD

**Issue by lj894** [Agile-Organization/recommendations#68]
Add 1 more column to the database schema called recommendation_id, when a record created, the recommendation_id generated automatically(auto increment). The recommendation_id can be used to query a certain record, or used to update or delete the record.
For example:
PUT on /recommendations/{recommendation_id} to update a record;
DELETE on /recommendations/{recommendation_id} to delete the record.

**Comment by sushanthsamala** [comment]
@lj894 Will the recommendation details like rel id, id, status will be sent in the request body for PUT and DELETE?

**Comment by lj894** [comment]
We can probably drop this issue since professor provided an alternative solution.
