### ISSUE TITLE
Base API should return meaningful content

### ISSUE THREAD

**Issue by lj894** [Agile-Organization/recommendations#89]
**As a** developer  
**I need** call /
**So that** it returns the document on how to use the service

**Assumptions:** 
* all the APIs are implemented properly

**Acceptance Criteria:**
```
When I call /
Then it returns the README document on all the APIs in recommendation service and how to call them.
```

**Comment by MinervaMint** [comment]
Should the document be at /recommendations or at the root (https://nyu-recommendation-service-f20.us-south.cf.appdomain.cloud)?

**Comment by lj894** [comment]
Yeah you're right I will update

**Comment by sushanthsamala** [comment]
Since we will be displaying single page UI, this github issue can be deprecated.
